import "./globals.css";
import Footer from "@/components/common/Footer";

export const metadata = {
  title: "Fitness Point",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <Header/> */}
        {children}
        <Footer/>
      </body>
    </html>
  );
}
